blank_issues_enabled: true
contact_links:
  - name: test
    url: https://github.com/devpang20/issue_test
    about: test
  - name: tset
    url: https://github.com/devpang20/issue_test
    about: test
